// react
import { ReactNode, useEffect } from 'react';

// next js
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Link from 'next/link';
import Image from 'next/image';

// i18next
import { useTranslation, Trans } from 'next-i18next';

// components
import Typography from '@src/components/Typography';
import Button from '@src/components/Button';

interface IProps {
  children?: ReactNode;
}

const Home: React.FC<IProps> = () => {
  const router = useRouter();
  const { t } = useTranslation('common') as any;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="">Hello world!</div>
    </>
  );
};

export default Home;
