export const countryCodes = [
  {
    name: 'Afghanistan',
    ar_name: 'أفغانستان',
    dial_code: '+93',
    code: 'AF',
  },
  {
    name: 'Aland Islands',
    ar_name: 'جزر آلاند',
    dial_code: '+358',
    code: 'AX',
  },
  {
    name: 'Albania',
    ar_name: 'ألبانيا',
    dial_code: '+355',
    code: 'AL',
  },
  {
    name: 'Algeria',
    ar_name: 'الجزائر',
    dial_code: '+213',
    code: 'DZ',
  },
  {
    name: 'AmericanSamoa',
    ar_name: 'ساموا الأمريكية',
    dial_code: '+1684',
    code: 'AS',
  },
  {
    name: 'Andorra',
    ar_name: 'أندورا',
    dial_code: '+376',
    code: 'AD',
  },
  {
    name: 'Angola',
    ar_name: 'أنغولا',
    dial_code: '+244',
    code: 'AO',
  },
  {
    name: 'Anguilla',
    ar_name: 'أنغويلا',
    dial_code: '+1264',
    code: 'AI',
  },
  {
    name: 'Antarctica',
    ar_name: 'القارة القطبية الجنوبية',
    dial_code: '+672',
    code: 'AQ',
  },
  {
    name: 'Antigua and Barbuda',
    ar_name: 'أنتيغوا وبربودا',
    dial_code: '+1268',
    code: 'AG',
  },
  {
    name: 'Argentina',
    ar_name: 'الأرجنتين',
    dial_code: '+54',
    code: 'AR',
  },
  {
    name: 'Armenia',
    ar_name: 'أرمينيا',
    dial_code: '+374',
    code: 'AM',
  },
  {
    name: 'Aruba',
    ar_name: 'أروبا',
    dial_code: '+297',
    code: 'AW',
  },
  {
    name: 'Australia',
    ar_name: 'أستراليا',
    dial_code: '+61',
    code: 'AU',
  },
  {
    name: 'Austria',
    ar_name: 'النمسا',
    dial_code: '+43',
    code: 'AT',
  },
  {
    name: 'Azerbaijan',
    ar_name: 'أذربيجان',
    dial_code: '+994',
    code: 'AZ',
  },
  {
    name: 'Bahamas',
    ar_name: 'الباهاماس',
    dial_code: '+1242',
    code: 'BS',
  },
  {
    name: 'Bahrain',
    ar_name: 'البحرين',
    dial_code: '+973',
    code: 'BH',
  },
  {
    name: 'Bangladesh',
    ar_name: 'بنغلاديش',
    dial_code: '+880',
    code: 'BD',
  },
  {
    name: 'Barbados',
    ar_name: 'بربادو',
    dial_code: '+1246',
    code: 'BB',
  },
  {
    name: 'Belarus',
    dial_code: '+375',
    code: 'BY',
    ar_name: 'روسيا البيضاء',
  },
  {
    name: 'Belgium',
    dial_code: '+32',
    code: 'BE',
    ar_name: 'بلجيكا',
  },
  {
    name: 'Belize',
    dial_code: '+501',
    code: 'BZ',
    ar_name: 'بليز',
  },
  {
    name: 'Benin',
    dial_code: '+229',
    code: 'BJ',
    ar_name: 'بنين',
  },
  {
    name: 'Bermuda',
    dial_code: '+1441',
    code: 'BM',
    ar_name: 'برمودا',
  },
  {
    name: 'Bhutan',
    dial_code: '+975',
    code: 'BT',
    ar_name: 'بوتان',
  },
  {
    name: 'Bolivia, Plurinational State of',
    dial_code: '+591',
    code: 'BO',
    ar_name: 'بوليفيا',
  },
  {
    name: 'Bosnia and Herzegovina',
    dial_code: '+387',
    code: 'BA',
    ar_name: 'البوسنة والهرسك',
  },
  {
    name: 'Botswana',
    dial_code: '+267',
    code: 'BW',
    ar_name: 'بتسوانا',
  },
  {
    name: 'Brazil',
    dial_code: '+55',
    code: 'BR',
    ar_name: 'البرازيل',
  },
  {
    name: 'British Indian Ocean Territory',
    dial_code: '+246',
    code: 'IO',
    ar_name: 'إقليم المحيط الهندي البريطاني',
  },
  {
    name: 'Brunei Darussalam',
    dial_code: '+673',
    code: 'BN',
    ar_name: 'بروناي',
  },
  {
    name: 'Bulgaria',
    dial_code: '+359',
    code: 'BG',
    ar_name: 'بلغاريا',
  },
  {
    name: 'Burkina Faso',
    dial_code: '+226',
    code: 'BF',
    ar_name: 'بوركينا فاسو',
  },
  {
    name: 'Burundi',
    dial_code: '+257',
    code: 'BI',
    ar_name: 'بوروندي',
  },
  {
    name: 'Cambodia',
    dial_code: '+855',
    code: 'KH',
    ar_name: 'كمبوديا',
  },
  {
    name: 'Cameroon',
    dial_code: '+237',
    code: 'CM',
    ar_name: 'الكاميرون',
  },
  {
    name: 'Canada',
    dial_code: '+1',
    code: 'CA',
    ar_name: 'كندا',
  },
  {
    name: 'Cape Verde',
    dial_code: '+238',
    code: 'CV',
    ar_name: 'الرأس الأخضر',
  },
  {
    name: 'Cayman Islands',
    dial_code: '+ 345',
    code: 'KY',
    ar_name: 'جزر كايمان',
  },
  {
    name: 'Central African Republic',
    dial_code: '+236',
    code: 'CF',
    ar_name: 'جمهورية أفريقيا الوسطى',
  },
  {
    name: 'Chad',
    dial_code: '+235',
    code: 'TD',
    ar_name: 'تشاد',
  },
  {
    name: 'Chile',
    dial_code: '+56',
    code: 'CL',
    ar_name: 'تشيلي',
  },
  {
    name: 'China',
    dial_code: '+86',
    code: 'CN',
    ar_name: 'الصين',
  },
  {
    name: 'Christmas Island',
    dial_code: '+61',
    code: 'CX',
    ar_name: 'جزيرة الكريسماس',
  },
  {
    name: 'Cocos (Keeling) Islands',
    dial_code: '+61',
    code: 'CC',
    ar_name: 'جزر كوكوس (كيلينغ)',
  },
  {
    name: 'Colombia',
    dial_code: '+57',
    code: 'CO',
    ar_name: 'كولومبيا',
  },
  {
    name: 'Comoros',
    dial_code: '+269',
    code: 'KM',
    ar_name: 'جزر القمر',
  },
  {
    name: 'Congo',
    dial_code: '+242',
    code: 'CG',
    ar_name: 'جمهورية الكونغو',
  },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    dial_code: '+243',
    code: 'CD',
    ar_name: 'جمهورية الكونغو الديمقراطية',
  },
  {
    name: 'Cook Islands',
    dial_code: '+682',
    code: 'CK',
    ar_name: 'جزر كوك',
  },
  {
    name: 'Costa Rica',
    dial_code: '+506',
    code: 'CR',
    ar_name: 'كوستاريكا',
  },
  {
    name: "Cote d'Ivoire",
    dial_code: '+225',
    code: 'CI',
    ar_name: 'ساحل العاج',
  },
  {
    name: 'Croatia',
    dial_code: '+385',
    code: 'HR',
    ar_name: 'كرواتيا',
  },
  {
    name: 'Cuba',
    dial_code: '+53',
    code: 'CU',
    ar_name: 'كوبا',
  },
  {
    name: 'Cyprus',
    dial_code: '+357',
    code: 'CY',
    ar_name: 'قبرص',
  },
  {
    name: 'Czech Republic',
    dial_code: '+420',
    code: 'CZ',
    ar_name: 'جمهورية التشيك',
  },
  {
    name: 'Denmark',
    dial_code: '+45',
    code: 'DK',
    ar_name: 'الدانمرك',
  },
  {
    name: 'Djibouti',
    dial_code: '+253',
    code: 'DJ',
    ar_name: 'جيبوتي',
  },
  {
    name: 'Dominica',
    dial_code: '+1767',
    code: 'DM',
    ar_name: 'دومينيكا',
  },
  {
    name: 'Dominican Republic',
    dial_code: '+1849',
    code: 'DO',
    ar_name: 'جمهورية الدومينيكان',
  },
  {
    name: 'Ecuador',
    dial_code: '+593',
    code: 'EC',
    ar_name: 'إكوادور',
  },
  {
    name: 'Egypt',
    dial_code: '+20',
    code: 'EG',
    ar_name: 'مصر',
  },
  {
    name: 'El Salvador',
    dial_code: '+503',
    code: 'SV',
    ar_name: 'السلفادور',
  },
  {
    name: 'Equatorial Guinea',
    dial_code: '+240',
    code: 'GQ',
    ar_name: 'غينيا الاستوائية',
  },
  {
    name: 'Eritrea',
    dial_code: '+291',
    code: 'ER',
    ar_name: 'إريتريا',
  },
  {
    name: 'Estonia',
    dial_code: '+372',
    code: 'EE',
    ar_name: 'إستونيا',
  },
  {
    name: 'Ethiopia',
    dial_code: '+251',
    code: 'ET',
    ar_name: 'إثيوبيا',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    dial_code: '+500',
    code: 'FK',
    ar_name: 'جزر فوكلاند',
  },
  {
    name: 'Faroe Islands',
    dial_code: '+298',
    code: 'FO',
    ar_name: 'جزر فارو',
  },
  {
    name: 'Fiji',
    dial_code: '+679',
    code: 'FJ',
    ar_name: 'فيجي',
  },
  {
    name: 'Finland',
    dial_code: '+358',
    code: 'FI',
    ar_name: 'فنلندا',
  },
  {
    name: 'France',
    dial_code: '+33',
    code: 'FR',
    ar_name: 'فرنسا',
  },
  {
    name: 'French Guiana',
    dial_code: '+594',
    code: 'GF',
    ar_name: 'غويانا الفرنسية',
  },
  {
    name: 'French Polynesia',
    dial_code: '+689',
    code: 'PF',
    ar_name: 'بولينزيا الفرنسية',
  },
  {
    name: 'Gabon',
    dial_code: '+241',
    code: 'GA',
    ar_name: 'الجابون',
  },
  {
    name: 'Gambia',
    dial_code: '+220',
    code: 'GM',
    ar_name: 'غامبيا',
  },
  {
    name: 'Georgia',
    dial_code: '+995',
    code: 'GE',
    ar_name: 'جورجيا',
  },
  {
    name: 'Germany',
    dial_code: '+49',
    code: 'DE',
    ar_name: 'ألمانيا',
  },
  {
    name: 'Ghana',
    dial_code: '+233',
    code: 'GH',
    ar_name: 'غانا',
  },
  {
    name: 'Gibraltar',
    dial_code: '+350',
    code: 'GI',
    ar_name: 'جبل طارق',
  },
  {
    name: 'Greece',
    dial_code: '+30',
    code: 'GR',
    ar_name: 'اليونان',
  },
  {
    name: 'Greenland',
    dial_code: '+299',
    code: 'GL',
    ar_name: 'جرينلاند',
  },
  {
    name: 'Grenada',
    dial_code: '+1473',
    code: 'GD',
    ar_name: 'غرينادا',
  },
  {
    name: 'Guadeloupe',
    dial_code: '+590',
    code: 'GP',
    ar_name: 'جوادلوب',
  },
  {
    name: 'Guam',
    dial_code: '+1671',
    code: 'GU',
    ar_name: 'غوام',
  },
  {
    name: 'Guatemala',
    dial_code: '+502',
    code: 'GT',
    ar_name: 'غواتيمالا',
  },
  {
    name: 'Guernsey',
    dial_code: '+44',
    code: 'GG',
    ar_name: 'غيرنزي',
  },
  {
    name: 'Guinea',
    dial_code: '+224',
    code: 'GN',
    ar_name: 'غينيا',
  },
  {
    name: 'Guinea-Bissau',
    dial_code: '+245',
    code: 'GW',
    ar_name: 'غينيا بيساو',
  },
  {
    name: 'Guyana',
    dial_code: '+595',
    code: 'GY',
    ar_name: 'غيانا',
  },
  {
    name: 'Haiti',
    dial_code: '+509',
    code: 'HT',
    ar_name: 'هايتي',
  },
  {
    name: 'Holy See (Vatican City State)',
    dial_code: '+379',
    code: 'VA',
    ar_name: 'الكرسي الرسولي',
  },
  {
    name: 'Honduras',
    dial_code: '+504',
    code: 'HN',
    ar_name: 'هندوراس',
  },
  {
    name: 'Hong Kong',
    dial_code: '+852',
    code: 'HK',
    ar_name: 'هونغ كونغ',
  },
  {
    name: 'Hungary',
    dial_code: '+36',
    code: 'HU',
    ar_name: 'المجر',
  },
  {
    name: 'Iceland',
    dial_code: '+354',
    code: 'IS',
    ar_name: 'آيسلندا',
  },
  {
    name: 'India',
    dial_code: '+91',
    code: 'IN',
    ar_name: 'الهند',
  },
  {
    name: 'Indonesia',
    dial_code: '+62',
    code: 'ID',
    ar_name: 'إندونيسيا',
  },
  {
    name: 'Iran, Islamic Republic of Iran',
    dial_code: '+98',
    code: 'IR',
    ar_name: 'إيران',
  },
  {
    name: 'Iraq',
    dial_code: '+964',
    code: 'IQ',
    ar_name: 'العراق',
  },
  {
    name: 'Ireland',
    dial_code: '+353',
    code: 'IE',
    ar_name: 'أيرلندا',
  },
  {
    name: 'Isle of Man',
    dial_code: '+44',
    code: 'IM',
    ar_name: 'جزيرة مان',
  },
  {
    name: 'Israel',
    dial_code: '+972',
    code: 'IL',
    ar_name: 'إسرائيل',
  },
  {
    name: 'Italy',
    dial_code: '+39',
    code: 'IT',
    ar_name: 'إيطاليا',
  },
  {
    name: 'Jamaica',
    dial_code: '+1876',
    code: 'JM',
    ar_name: 'جامايكا',
  },
  {
    name: 'Japan',
    dial_code: '+81',
    code: 'JP',
    ar_name: 'اليابان',
  },
  {
    name: 'Jersey',
    dial_code: '+44',
    code: 'JE',
    ar_name: 'جيرسي',
  },
  {
    name: 'Jordan',
    dial_code: '+962',
    code: 'JO',
    ar_name: 'الأردن',
  },
  {
    name: 'Kazakhstan',
    dial_code: '+77',
    code: 'KZ',
    ar_name: 'كازاخستان',
  },
  {
    name: 'Kenya',
    dial_code: '+254',
    code: 'KE',
    ar_name: 'كينيا',
  },
  {
    name: 'Kiribati',
    dial_code: '+686',
    code: 'KI',
    ar_name: 'كيريباتي',
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: '+850',
    code: 'KP',
    ar_name: 'كوريا الشمالية',
  },
  {
    name: 'Korea, Republic of South Korea',
    dial_code: '+82',
    code: 'KR',
    ar_name: 'كوريا الجنوبية',
  },
  {
    name: 'Kuwait',
    dial_code: '+965',
    code: 'KW',
    ar_name: 'الكويت',
  },
  {
    name: 'Kyrgyzstan',
    dial_code: '+996',
    code: 'KG',
    ar_name: 'قيرغيزستان',
  },
  {
    name: 'Laos',
    dial_code: '+856',
    code: 'LA',
    ar_name: 'لاوس',
  },
  {
    name: 'Latvia',
    dial_code: '+371',
    code: 'LV',
    ar_name: 'لاتفيا',
  },
  {
    name: 'Lebanon',
    dial_code: '+961',
    code: 'LB',
    ar_name: 'لبنان',
  },
  {
    name: 'Lesotho',
    dial_code: '+266',
    code: 'LS',
    ar_name: 'ليسوتو',
  },
  {
    name: 'Liberia',
    dial_code: '+231',
    code: 'LR',
    ar_name: 'ليبيريا',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    dial_code: '+218',
    code: 'LY',
    ar_name: 'ليبيا',
  },
  {
    name: 'Liechtenstein',
    dial_code: '+423',
    code: 'LI',
    ar_name: 'ليختنشتاين',
  },
  {
    name: 'Lithuania',
    dial_code: '+370',
    code: 'LT',
    ar_name: 'ليتوانيا',
  },
  {
    name: 'Luxembourg',
    dial_code: '+352',
    code: 'LU',
    ar_name: 'لوكسمبورغ',
  },
  {
    name: 'Macao',
    dial_code: '+853',
    code: 'MO',
    ar_name: 'ماكاو',
  },
  {
    name: 'Macedonia',
    dial_code: '+389',
    code: 'MK',
    ar_name: 'مقدونيا',
  },
  {
    name: 'Madagascar',
    dial_code: '+261',
    code: 'MG',
    ar_name: 'مدغشقر',
  },
  {
    name: 'Malawi',
    dial_code: '+265',
    code: 'MW',
    ar_name: 'مالاوي',
  },
  {
    name: 'Malaysia',
    dial_code: '+60',
    code: 'MY',
    ar_name: 'ماليزيا',
  },
  {
    name: 'Maldives',
    dial_code: '+960',
    code: 'MV',
    ar_name: 'جزر المالديف',
  },
  {
    name: 'Mali',
    dial_code: '+223',
    code: 'ML',
    ar_name: 'مالي',
  },
  {
    name: 'Malta',
    dial_code: '+356',
    code: 'MT',
    ar_name: 'مالطا',
  },
  {
    name: 'Marshall Islands',
    dial_code: '+692',
    code: 'MH',
    ar_name: 'جزر مارشال',
  },
  {
    name: 'Martinique',
    dial_code: '+596',
    code: 'MQ',
    ar_name: 'مارتينيك',
  },
  {
    name: 'Mauritania',
    dial_code: '+222',
    code: 'MR',
    ar_name: 'موريتانيا',
  },
  {
    name: 'Mauritius',
    dial_code: '+230',
    code: 'MU',
    ar_name: 'موريشيوس',
  },
  {
    name: 'Mayotte',
    dial_code: '+262',
    code: 'YT',
    ar_name: 'مايوت',
  },
  {
    name: 'Mexico',
    dial_code: '+52',
    code: 'MX',
    ar_name: 'المكسيك',
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    dial_code: '+691',
    code: 'FM',
    ar_name: 'ميكرونيزيا، ولايات ميكرونيزيا المتحدة',
  },
  {
    name: 'Moldova',
    dial_code: '+373',
    code: 'MD',
    ar_name: 'مولدوفا',
  },
  {
    name: 'Monaco',
    dial_code: '+377',
    code: 'MC',
    ar_name: 'موناكو',
  },
  {
    name: 'Mongolia',
    dial_code: '+976',
    code: 'MN',
    ar_name: 'منغوليا',
  },
  {
    name: 'Montenegro',
    dial_code: '+382',
    code: 'ME',
    ar_name: 'الجبل الأسود',
  },
  {
    name: 'Montserrat',
    dial_code: '+1664',
    code: 'MS',
    ar_name: 'مونتسيرات',
  },
  {
    name: 'Morocco',
    dial_code: '+212',
    code: 'MA',
    ar_name: 'المغرب',
  },
  {
    name: 'Mozambique',
    dial_code: '+258',
    code: 'MZ',
    ar_name: 'موزمبيق',
  },
  {
    name: 'Myanmar',
    dial_code: '+95',
    code: 'MM',
    ar_name: 'ميانمار',
  },
  {
    name: 'Namibia',
    dial_code: '+264',
    code: 'NA',
    ar_name: 'ناميبيا',
  },
  {
    name: 'Nauru',
    dial_code: '+674',
    code: 'NR',
    ar_name: 'ناورو',
  },
  {
    name: 'Nepal',
    dial_code: '+977',
    code: 'NP',
    ar_name: 'نيبال',
  },
  {
    name: 'Netherlands',
    dial_code: '+31',
    code: 'NL',
    ar_name: 'هولندا',
  },
  {
    name: 'Netherlands Antilles',
    dial_code: '+599',
    code: 'AN',
    ar_name: 'جزر الأنتيل الهولندية',
  },
  {
    name: 'New Caledonia',
    dial_code: '+687',
    code: 'NC',
    ar_name: 'كاليدونيا الجديدة',
  },
  {
    name: 'New Zealand',
    dial_code: '+64',
    code: 'NZ',
    ar_name: 'نيوزيلندا',
  },
  {
    name: 'Nicaragua',
    dial_code: '+505',
    code: 'NI',
    ar_name: 'نيكاراجوا',
  },
  {
    name: 'Niger',
    dial_code: '+227',
    code: 'NE',
    ar_name: 'النيجر',
  },
  {
    name: 'Nigeria',
    dial_code: '+234',
    code: 'NG',
    ar_name: 'نيجيريا',
  },
  {
    name: 'Niue',
    dial_code: '+683',
    code: 'NU',
    ar_name: 'نييوي',
  },
  {
    name: 'Norfolk Island',
    dial_code: '+672',
    code: 'NF',
    ar_name: 'جزيرة نورفولك',
  },
  {
    name: 'Northern Mariana Islands',
    dial_code: '+1670',
    code: 'MP',
    ar_name: 'جزر ماريانا الشمالية',
  },
  {
    name: 'Norway',
    dial_code: '+47',
    code: 'NO',
    ar_name: 'النرويج',
  },
  {
    name: 'Oman',
    dial_code: '+968',
    code: 'OM',
    ar_name: 'عمان',
  },
  {
    name: 'Pakistan',
    dial_code: '+92',
    code: 'PK',
    ar_name: 'باكستان',
  },
  {
    name: 'Palau',
    dial_code: '+680',
    code: 'PW',
    ar_name: 'بالاو',
  },
  {
    name: 'Palestinian Territory, Occupied',
    dial_code: '+970',
    code: 'PS',
    ar_name: 'فلسطين',
  },
  {
    name: 'Panama',
    dial_code: '+507',
    code: 'PA',
    ar_name: 'بنما',
  },
  {
    name: 'Papua New Guinea',
    dial_code: '+675',
    code: 'PG',
    ar_name: 'بابوا غينيا الجديدة',
  },
  {
    name: 'Paraguay',
    dial_code: '+595',
    code: 'PY',
    ar_name: 'باراغواي',
  },
  {
    name: 'Peru',
    dial_code: '+51',
    code: 'PE',
    ar_name: 'بيرو',
  },
  {
    name: 'Philippines',
    dial_code: '+63',
    code: 'PH',
    ar_name: 'الفلبين',
  },
  {
    name: 'Pitcairn',
    dial_code: '+872',
    code: 'PN',
    ar_name: 'بتكايرن',
  },
  {
    name: 'Poland',
    dial_code: '+48',
    code: 'PL',
    ar_name: 'بولندا',
  },
  {
    name: 'Portugal',
    dial_code: '+351',
    code: 'PT',
    ar_name: 'البرتغال',
  },
  {
    name: 'Puerto Rico',
    dial_code: '+1939',
    code: 'PR',
    ar_name: 'بورتوريكو',
  },
  {
    name: 'Qatar',
    dial_code: '+974',
    code: 'QA',
    ar_name: 'قطر',
  },
  {
    name: 'Romania',
    dial_code: '+40',
    code: 'RO',
    ar_name: 'رومانيا',
  },
  {
    name: 'Russia',
    dial_code: '+7',
    code: 'RU',
    ar_name: 'روسيا',
  },
  {
    name: 'Rwanda',
    dial_code: '+250',
    code: 'RW',
    ar_name: 'رواندا',
  },
  {
    name: 'Reunion',
    dial_code: '+262',
    code: 'RE',
    ar_name: 'ريونيون',
  },
  {
    name: 'Saint Barthelemy',
    dial_code: '+590',
    code: 'BL',
    ar_name: 'سان بارتيليمي',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    dial_code: '+290',
    code: 'SH',
    ar_name: 'سانت هيلينا، أسينشين وتريستان دا كونا',
  },
  {
    name: 'Saint Kitts and Nevis',
    dial_code: '+1869',
    code: 'KN',
    ar_name: 'سانت كيتس ونيفيس',
  },
  {
    name: 'Saint Lucia',
    dial_code: '+1758',
    code: 'LC',
    ar_name: 'سانت لوسيا',
  },
  {
    name: 'Saint Martin',
    dial_code: '+590',
    code: 'MF',
    ar_name: 'سانت مارتن',
  },
  {
    name: 'Saint Pierre and Miquelon',
    dial_code: '+508',
    code: 'PM',
    ar_name: 'سانت بيير وميكلون',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    dial_code: '+1784',
    code: 'VC',
    ar_name: 'سانت فينسنت وجزر غرينادين',
  },
  {
    name: 'Samoa',
    dial_code: '+685',
    code: 'WS',
    ar_name: 'ساموا',
  },
  {
    name: 'San Marino',
    dial_code: '+378',
    code: 'SM',
    ar_name: 'سان مارينو',
  },
  {
    name: 'Sao Tome and Principe',
    dial_code: '+239',
    code: 'ST',
    ar_name: 'ساو تومي وبرينسيبي',
  },
  {
    name: 'Saudi Arabia',
    dial_code: '+966',
    code: 'SA',
    ar_name: 'المملكة العربية السعودية',
  },
  {
    name: 'Senegal',
    dial_code: '+221',
    code: 'SN',
    ar_name: 'السنغال',
  },
  {
    name: 'Serbia',
    dial_code: '+381',
    code: 'RS',
    ar_name: 'صربيا',
  },
  {
    name: 'Seychelles',
    dial_code: '+248',
    code: 'SC',
    ar_name: 'سيشيل',
  },
  {
    name: 'Sierra Leone',
    dial_code: '+232',
    code: 'SL',
    ar_name: 'سيراليون',
  },
  {
    name: 'Singapore',
    dial_code: '+65',
    code: 'SG',
    ar_name: 'سنغافورة',
  },
  {
    name: 'Slovakia',
    dial_code: '+421',
    code: 'SK',
    ar_name: 'سلوفاكيا',
  },
  {
    name: 'Slovenia',
    dial_code: '+386',
    code: 'SI',
    ar_name: 'سلوفينيا',
  },
  {
    name: 'Solomon Islands',
    dial_code: '+677',
    code: 'SB',
    ar_name: 'جزر سليمان',
  },
  {
    name: 'Somalia',
    dial_code: '+252',
    code: 'SO',
    ar_name: 'الصومال',
  },
  {
    name: 'South Africa',
    dial_code: '+27',
    code: 'ZA',
    ar_name: 'جنوب أفريقيا',
  },
  {
    name: 'South Sudan',
    dial_code: '+211',
    code: 'SS',
    ar_name: 'جنوب السودان',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    dial_code: '+500',
    code: 'GS',
    ar_name: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
  },
  {
    name: 'Spain',
    dial_code: '+34',
    code: 'ES',
    ar_name: 'إسبانيا',
  },
  {
    name: 'Sri Lanka',
    dial_code: '+94',
    code: 'LK',
    ar_name: 'سريلانكا',
  },
  {
    name: 'Sudan',
    dial_code: '+249',
    code: 'SD',
    ar_name: 'السودان',
  },
  {
    name: 'Suriname',
    dial_code: '+597',
    code: 'SR',
    ar_name: 'سورينام',
  },
  {
    name: 'Svalbard and Jan Mayen',
    dial_code: '+47',
    code: 'SJ',
    ar_name: 'سفالبارد وجان مايان',
  },
  {
    name: 'Swaziland',
    ar_name: 'سوازيلاند',
    dial_code: '+268',
    code: 'SZ',
  },
  {
    name: 'Sweden',
    ar_name: 'السويد',
    dial_code: '+46',
    code: 'SE',
  },
  {
    name: 'Switzerland',
    ar_name: 'سويسرا',
    dial_code: '+41',
    code: 'CH',
  },
  {
    name: 'Syrian Arab Republic',
    ar_name: 'الجمهورية العربية السورية',
    dial_code: '+963',
    code: 'SY',
  },
  {
    name: 'Taiwan',
    ar_name: 'تايوان',
    dial_code: '+886',
    code: 'TW',
  },
  {
    name: 'Tajikistan',
    ar_name: 'طاجيكستان',
    dial_code: '+992',
    code: 'TJ',
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    ar_name: 'تنزانيا',
    dial_code: '+255',
    code: 'TZ',
  },
  {
    name: 'Thailand',
    ar_name: 'تايلاند',
    dial_code: '+66',
    code: 'TH',
  },
  {
    name: 'Timor-Leste',
    ar_name: 'تيمور الشرقية',
    dial_code: '+670',
    code: 'TL',
  },
  {
    name: 'Togo',
    ar_name: 'توغو',
    dial_code: '+228',
    code: 'TG',
  },
  {
    name: 'Tokelau',
    ar_name: 'توكيلاو',
    dial_code: '+690',
    code: 'TK',
  },
  {
    name: 'Tonga',
    ar_name: 'تونجا',
    dial_code: '+676',
    code: 'TO',
  },
  {
    name: 'Trinidad and Tobago',
    ar_name: 'ترينيداد وتوباغو',
    dial_code: '+1868',
    code: 'TT',
  },
  {
    name: 'Tunisia',
    ar_name: 'تونس',
    dial_code: '+216',
    code: 'TN',
  },
  {
    name: 'Turkey',
    ar_name: 'تركيا',
    dial_code: '+90',
    code: 'TR',
  },
  {
    name: 'Turkmenistan',
    ar_name: 'تركمانستان',
    dial_code: '+993',
    code: 'TM',
  },
  {
    name: 'Turks and Caicos Islands',
    ar_name: 'جزر توركس وكايكوس',
    dial_code: '+1649',
    code: 'TC',
  },
  {
    name: 'Tuvalu',
    ar_name: 'توفالو',
    dial_code: '+688',
    code: 'TV',
  },
  {
    name: 'Uganda',
    ar_name: 'أوغندا',
    dial_code: '+256',
    code: 'UG',
  },
  {
    name: 'Ukraine',
    ar_name: 'أوكرانيا',
    dial_code: '+380',
    code: 'UA',
  },
  {
    name: 'United Arab Emirates',
    dial_code: '+971',
    code: 'AE',
    ar_name: 'الإمارات العربية المتحدة',
  },
  {
    name: 'United Kingdom',
    dial_code: '+44',
    code: 'GB',
    ar_name: 'المملكة المتحدة',
  },
  {
    name: 'United States',
    dial_code: '+1',
    code: 'US',
    ar_name: 'الولايات المتحدة الأمريكية',
  },
  {
    name: 'Uruguay',
    dial_code: '+598',
    code: 'UY',
    ar_name: 'الأوروغواي',
  },
  {
    name: 'Uzbekistan',
    dial_code: '+998',
    code: 'UZ',
    ar_name: 'أوزبكستان',
  },
  {
    name: 'Vanuatu',
    dial_code: '+678',
    code: 'VU',
    ar_name: 'فانواتو',
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    dial_code: '+58',
    code: 'VE',
    ar_name: 'فنزويلا، جمهورية بوليفارية',
  },
  {
    name: 'Vietnam',
    dial_code: '+84',
    code: 'VN',
    ar_name: 'فيتنام',
  },
  {
    name: 'Virgin Islands, British',
    dial_code: '+1284',
    code: 'VG',
    ar_name: 'جزر فيرجن البريطانية',
  },
  {
    name: 'Virgin Islands, U.S.',
    dial_code: '+1340',
    code: 'VI',
    ar_name: 'جزر فيرجن الأمريكية',
  },
  {
    name: 'Wallis and Futuna',
    dial_code: '+681',
    code: 'WF',
    ar_name: 'والس وفوتونا',
  },
  {
    name: 'Yemen',
    dial_code: '+967',
    code: 'YE',
    ar_name: 'اليمن',
  },
  {
    name: 'Zambia',
    dial_code: '+260',
    code: 'ZM',
    ar_name: 'زامبيا',
  },
  {
    name: 'Zimbabwe',
    dial_code: '+263',
    code: 'ZW',
    ar_name: 'زيمبابوي',
  },
];
